apiVersion: apps/v1
kind: Deployment
metadata:
  name: myclient
spec:
  selector:
    matchLabels:
      app: myclient
  template:
    metadata:
      labels:
        app: myclient
    spec:
      containers:
        - name: client
          args:
            - --myservice-address=myservice
